#!/usr/bin/env python3
"""
Generate static pronunciation audio for every vocabulary term and every
click-to-translate dictionary word, so the app has a guaranteed, browser-
independent fallback (plays via HTML5 Audio — works on Safari/iPhone, Android,
and even engine-less Linux desktops, fully offline).

Uses edge-tts (free Microsoft neural voices, no API key).

Run it via the wrapper, which manages an isolated virtualenv for you (no
system-wide pip install — avoids Ubuntu's PEP 668 error):

    npm run audio
    # or directly:
    bash scripts/run-audio.sh

Outputs:
    public/audio/en/<hash>.mp3, public/audio/zh/<hash>.mp3
    src/data/vocabAudio.generated.ts   (term -> relative path manifest)
"""
import asyncio
import hashlib
import json
import re
import sys
from pathlib import Path

try:
    import edge_tts
except ImportError:
    sys.exit("edge-tts is not installed. Run: pip install edge-tts")

ROOT = Path(__file__).resolve().parent.parent
VOCAB_TS = ROOT / "src" / "data" / "vocabData.ts"
DICT_TS = ROOT / "src" / "lib" / "dictionary.ts"
AUDIO_DIR = ROOT / "public" / "audio"
OUT_TS = ROOT / "src" / "data" / "vocabAudio.generated.ts"

# Neural voices per target language.
VOICE = {
    "en": "en-US-AriaNeural",
    "zh": "zh-CN-XiaoxiaoNeural",
}


def slug(lang: str, term: str) -> str:
    h = hashlib.sha1(f"{lang}:{term}".encode("utf-8")).hexdigest()[:12]
    return h


def collect_terms() -> dict[str, list[str]]:
    """Return {'en': [...], 'zh': [...]} of unique terms to synthesize."""
    vocab = VOCAB_TS.read_text(encoding="utf-8")

    # Split the file into the EN_WORDS and ZH_WORDS array bodies.
    def block(name: str) -> str:
        m = re.search(rf"const {name}: Word\[\] = \[(.*?)\n\];", vocab, re.S)
        return m.group(1) if m else ""

    def terms_in(body: str) -> list[str]:
        return re.findall(r'term:\s*"((?:[^"\\]|\\.)*)"', body)

    en = terms_in(block("EN_WORDS"))
    zh = terms_in(block("ZH_WORDS"))

    # Add click-to-translate dictionary words (English supplement only).
    dic = DICT_TS.read_text(encoding="utf-8")
    en_supp = re.findall(r'\bterm:\s*"((?:[^"\\]|\\.)*)"', dic)
    en += en_supp

    # De-duplicate, keep order.
    def dedupe(xs):
        seen, out = set(), []
        for x in xs:
            if x not in seen:
                seen.add(x)
                out.append(x)
        return out

    return {"en": dedupe(en), "zh": dedupe(zh)}


async def synth(term: str, lang: str, path: Path):
    communicate = edge_tts.Communicate(term, VOICE[lang])
    await communicate.save(str(path))


async def main():
    terms = collect_terms()
    manifest: dict[str, dict[str, str]] = {"en": {}, "zh": {}}

    for lang, words in terms.items():
        out_dir = AUDIO_DIR / lang
        out_dir.mkdir(parents=True, exist_ok=True)
        for term in words:
            fname = f"{slug(lang, term)}.mp3"
            path = out_dir / fname
            rel = f"audio/{lang}/{fname}"
            manifest[lang][term] = rel
            if path.exists():
                continue
            try:
                await synth(term, lang, path)
                print(f"[ok] {lang} {term} -> {rel}", file=sys.stderr)
            except Exception as e:  # noqa: BLE001
                print(f"[skip] {lang} {term}: {e}", file=sys.stderr)
                manifest[lang].pop(term, None)

    header = (
        "// AUTO-GENERATED by scripts/generate-vocab-audio.py — do not edit.\n"
        "// Maps a target-language term to a static audio clip (relative to\n"
        "// import.meta.env.BASE_URL). Used as an offline / no-system-voice\n"
        "// fallback for pronunciation. Regenerate: npm run audio\n\n"
        "import type { LanguageCode } from \"./types\";\n\n"
        "export const VOCAB_AUDIO: Record<LanguageCode, Record<string, string>> =\n"
    )
    OUT_TS.write_text(
        header + json.dumps(manifest, ensure_ascii=False, indent=2) + ";\n",
        encoding="utf-8",
    )
    total = sum(len(v) for v in manifest.values())
    print(f"[done] {total} clips, wrote {OUT_TS}", file=sys.stderr)


if __name__ == "__main__":
    asyncio.run(main())
